Add options to NiceButton to switch between filling available space and sizing to fit contents
steamclock/niceComponents pull request #67
Opened 2024-11-05 19:51 UTC by brendanlensink

This has come up a couple times where it's annoying to have buttons that won't size to fit their contents, so this PR adds two new params to the NiceButton constructor to allow for setting this.

# Breaking changes

none

# Non-breaking changes

Added two new params to the NiceButton constructor:
`maxWidth` allows you to set the width for the button. Default is `.infinity` to match old behaviour.
`textPadding` allows you to set the padding between the buttons contents and the border, which you need if you set the max width to anything other than infinity.

![Screenshot 2024-11-05 at 11 51 21 AM](https://github.com/user-attachments/assets/1edb9d49-6ec0-4aa4-8918-ee017cd88a68)

2024-11-05 21:05 UTC, mauriceschenk requested changes
Two small suggestions.
I was also trying to add an image to the right but it didn't work. Not sure if it's related to the changes.

2024-11-05 21:05 UTC, mauriceschenk commented on Sources/NiceComponents/Button/NiceButton.swift
> +           .frame(maxWidth: maxWidth)
I think we can get rid of the `maxWidth` parameter with the same result. We just have to add `nil` as the default value of `textPadding`.
![image](https://github.com/user-attachments/assets/b44f5040-a39b-43fc-ac8f-b7fe44889cc7)
```suggestion
           .frame(maxWidth: horizontalPadding == nil ? .infinity : nil)
```

2024-11-12 18:47 UTC, brendanlensink commented
Thanks for the feedback @mauriceschenk! Updated a bunch of things, and fixed the system image bug

2024-11-14 21:05 UTC, mauriceschenk approved these changes
🚢

2024-11-14 21:14 UTC, merged